FROM golang:1.14-buster AS builder
LABEL maintainer="Flávio Visetti Soares"
ENV SRC_DIR=/go/src/github.com/flaviovisetti/transaction-routine
WORKDIR $SRC_DIR
COPY . ./
RUN go get .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o /main .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=builder /main ./
EXPOSE 8000
RUN chmod +x ./main
ENTRYPOINT ["./main"]